insert into CURR_EXCHANGE(CURR_ID,CURR_FROM,CURR_TO,CURR_RATE,port) values(10001,'USD','INR',65,0);
insert into CURR_EXCHANGE(CURR_ID,CURR_FROM,CURR_TO,CURR_RATE,port) values(10002,'EUR','INR',75,0);
insert into CURR_EXCHANGE(CURR_ID,CURR_FROM,CURR_TO,CURR_RATE,port) values(10003,'AUD','INR',25,0);
insert into CURR_EXCHANGE(CURR_ID,CURR_FROM,CURR_TO,CURR_RATE,port) values(10004,'GBP','INR',88,0);
insert into CURR_EXCHANGE(CURR_ID,CURR_FROM,CURR_TO,CURR_RATE,port) values(10005,'JPY','INR',45,0);